### ISSUE TITLE
ResizeObserver 对象复用

### ISSUE THREAD

**Issue by hustcc** [hustcc/size-sensor#10]
@alanwei0 如果使用 ResizeObserver 做监听，那么可以重用一个 ResizeObserver 对象实例，可能能提升性能，较少内存消耗

**Comment by alanwei0** [comment]
@hustcc 
如果要复用ResizeObserver的话，那么任意一个被observe的元素改变size的时候都会触发下面的回调函数，然而在`entries`里包含所有被observe的元素，所以要找到实际变更的那个元素的话，就需要手动比较元素size是否变化，还需要增加一个数据结构维护元素上次变更后的大小。个人感觉这种改动之后收益并不明显，而且可能增加bug风险。
```javascript
const sizeChanged = currentSize => {
    // compare currentSize with oldSize
};

const resizeObserver = new ResizeObserver(entries => {
    // loop in all observed elements
    for (let entry of entries) {
        // we have to diff the size change by ourselves
        if (sizeChanged(entry.contentRect)) {
            // invoke corresponding callbacks
        }
    }
});
```

What's your opinion?

**Comment by hustcc** [comment]
sizeChanged 函数不需要吧，只要触发了就 触发 listener 就好了。只需要维护一个 element 和 listener 之间对应关系的。

**Comment by alanwei0** [comment]
必须要sizeChanged吧，不然怎么判断到底是哪一个element变化了
