### ISSUE TITLE
使用echarts-for-react中遇到一个问题，echarts-for-react 监听事件就是使用size-sensor， IE 11 下无法触发监听resize事件

### ISSUE THREAD

**Issue by fengyun2** [hustcc/size-sensor#11]
在线demo展示，用IE11 浏览器或者火狐浏览器 预览都可以复现，https://codesandbox.io/s/white-sun-s0juc

**Comment by hustcc** [comment]
你在 IE 11 上试一下 https://git.hust.cc/size-sensor/ 打开是否可以响应 resize 事件？我的 window 已经几年没有开机了。最开始做 size-sensor 的时候是测试过 IE9 的。

**Comment by fengyun2** [comment]
https://git.hust.cc/size-sensor/ 可以，但是echarts-for-react（ https://codesandbox.io/s/white-sun-s0juc ）在IE11 或 火狐浏览器都不可以响应，不知道是否是依赖 `size-sensor` 版本出了问题

**Comment by hustcc** [comment]
@fengyun2 你升级到最新的 ecahrts-for-react 试试看。理论上任意版本的 size-sensor 都处理过 IE 的

**Comment by fengyun2** [comment]
@hustcc 已经是最新版本了
![image](https://user-images.githubusercontent.com/8147202/79575001-a4e37600-80f3-11ea-9666-09a44ccb6f84.png)

**Comment by hustcc** [comment]
fixed v1.0.1
