### ISSUE TITLE
edge，ie浏览器在这种情况下，宽度改变，不会触发，高度改变会触发

### ISSUE THREAD

**Issue by muyake** [hustcc/size-sensor#13]
<!DOCTYPE html>

<html lang="en">

<head>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html,
    body,
    #container {
      height: 100%;
      width: 100%;
    }
  </style>
</head>

<body>
  <div id="container">

  </div>
  <script src="./size-sensor.min.js" type="application/javascript"></script>
  <script>
    var container = document.getElementById("container");
    sizeSensor.bind(container, () => {
      console.log("111");
    })
  </script>

</body>

</html>

**Comment by hustcc** [comment]
fixed v1.0.1
