### ISSUE TITLE
Size-sensor not responding to width changes in Safari (desktop)

### ISSUE THREAD

**Issue by colinatdatasembly** [hustcc/size-sensor#15]
This issue originated here: https://github.com/hustcc/echarts-for-react/issues/354

I'm using `echarts-for-react` version `2.0.15-beta.1` and the charts aren't resizing in Safari when only their width changes (when height changes both height and width are updated correctly). For context, it looks like `size-sensor` is using the object document rather than ResizeObserver.

I was able to make it work correctly by changing the style on the `<object>` element, switching `width:auto` to `width:100%`. I'm not sure if this is an issue with the way Safari calculates "auto" widths but it seems like this setting is preventing resize events from being triggered correctly.

**Comment by hustcc** [comment]
What's safari version, and can give me a live demo for test.

**Comment by colinatdatasembly** [comment]
Safari version `11.1.2`
Demo: https://codesandbox.io/s/exciting-mayer-gm4rc

In the demo, the chart is wrapped in a `react-resizable` component. Currently, resizing is restricted to the x-axis only and is not resizing when the width changes. If you remove the `axis="x"` prop on the `ResizableBox` component you can see that the chart resizes correctly when its height changes.

**Comment by hustcc** [comment]
fixed v1.0.1

**Comment by colinatdatasembly** [comment]
Thank you!

**Comment by dcantu96** [comment]
Hi can you checkout this demo: https://codesandbox.io/s/echarts-safari-issue-3cprm 
I think it's a bug or let me know what I am doing wrong. Basically I am setting a grid with 3 columns 1fr each. They will always expand so that's good, the problem is that they won't shrink.
