### ISSUE TITLE
[Bug] Focus is captured by the sensor object

### ISSUE THREAD

**Issue by AlexLomm** [hustcc/size-sensor#4]
Please see the reproduction of the bug here:

https://codesandbox.io/s/angry-surf-ci2r8

Steps to follow:

1. Focus the first input field
2. Hit tab multiple times
3. Check the console

**Expected result:** 
Second input field should be focused eventually.

**Actual result:** 
The sensor object traps the focus.

I submitted a [PR](https://github.com/hustcc/size-sensor/pull/3) which fixes the bug, please check.

**Comment by hustcc** [comment]
thank you very much, v0.2.5 released.
