### ISSUE TITLE
使用echarts-for-react中遇到一个问题（涉及到size-sensor）

### ISSUE THREAD

**Issue by darlk** [hustcc/size-sensor#9]
公司项目使用了echarts-for-react绘制echarts-wordcloud的功能，最近交付给客户使用时出现了一个奇怪现象，就是词云图生成后不断的闪烁。
        定位了客户机器，发现是在windows系统下，屏幕内容放大率大于100%时，就会出现这情况。我一路从echarts-for-react源码定位，发现只要注释掉size-sencor注册部分就不会出现这个闪烁。于是从github中找到你的size-sensor源码，定位到/lib/sensors/object.js中第43行，设置监听对象style时，就会导致resizeListener死循环执行。我看了下_constant.SensorStyle内容，只要把width:100%去掉或者改成width:auto，**echarts-wordcloud在windows下且屏幕内容放大率大于100%都不会出现resizeListener死循环的请况了**。
        同时查阅了下资料 https://www.auslogics.com/en/articles/fix-google-chrome-scaling-on-win-10/ ，发现chrome在屏幕内容放大率大于100%的情况下都有各种怪异行为，不知道是否跟chrome自身bug有关。我向github提一个pr，希望你能在百忙之中测试下

**Comment by hustcc** [comment]
可以帮忙看看使用的 size-sensor 版本是哪个吗？

**Comment by darlk** [comment]
版本号：0.2.4

**Comment by darlk** [comment]
我等下给你一个demo工程

**Comment by darlk** [comment]
https://codesandbox.io/s/eager-burnell-xubf6  这个试试

**Comment by hustcc** [comment]
+ size-sensor@0.2.6

可以在你的本地，将这个依赖更新到 0.2.6 版本，然后看看还会不会出问题！我这里没有 window~
